#ifndef INTERESTLEVEL_H
#define INTERESTLEVEL_H

enum interestLevel
{
    NO_INTEREST,
    LOW_INTEREST,
    MODERATE_INTEREST,
    HIGH_INTEREST,
    EXTREMELY_HIGH_INTEREST
};

#endif // INTERESTLEVEL_H
