#ifndef PURCHASECONFIRMATION_H
#define PURCHASECONFIRMATION_H

#include <QDialog>
#include <QString>
#include "home.h"
#include "productenum.h"

namespace Ui {
class purchaseConfirmation;
}

class purchaseConfirmation : public QDialog
{
    Q_OBJECT

public:

    /** fn
     * Constructor
     *      The basic constructor which is used to allow a customer to confirm a purchase.
     *
     * pass in QString name, product bought, MainWindow *window, QWidget *parent
     *      QString name   - The of the customer buying the product
     *      product bought - An enum value stating the product the customer is buying
     *
     *      MainWindow *window - A pointer back to the main window
     *      QWidget    *parent - A pointer generated by qt
     *
     * Postcondition:
     *      Creates the Qdialogs so that the customer can confirm the purchase
     */
    explicit purchaseConfirmation(QString name, product bought, MainWindow *window, QWidget *parent = 0);
    ~purchaseConfirmation();

private slots:

    /** fn
     * on_acceptButtonBox_accepted
     *      This is the slot that get executed when the user press ok
     *
     * Postcondition:
     *      If the user press ok, then the productOrders table get updated to show the purchase the customer
     *      made, and the QDialog closes. If the user press cancel then the QDialog closes and no other
     *      processing is done.
     */
    void on_confirmationButtonBox_accepted();

private:
    Ui::purchaseConfirmation *ui; //!Qt's generated ui pointer to access the widgets inside this window

    QString customerName; //!The name of the customer making the purchase

    product purchase; //!An enum value that state what product the customer is buying

    MainWindow *home; //!A pointer back to the main window
};

#endif // PURCHASECONFIRMATION_H
