#ifndef SEARCHDATABASE_H
#define SEARCHDATABASE_H

#include <QDialog>
#include "home.h"

namespace Ui {
class SearchDatabase;
}

class SearchDatabase : public QDialog
{
    Q_OBJECT

public:

    /** fn
     * Constructor
     *      The basic constructor which is used to search the database.
     *
     * pass MainWindow *window, QWidget *parent
     *      MainWindow *window - A pointer back to the main window
     *      QWidget    *parent - A pointer generated by qt
     *
     * Postcondition:
     *      Creates the Qdialogs so that the user can input the name of the customer they are looking for
     */
    explicit SearchDatabase(MainWindow *window, QWidget *parent = nullptr);
    ~SearchDatabase();

private slots:

    /** fn
     * on_buttonBox_accepted
     *      This the slot that is executed when the user press ok. Since the window may or may close when the user press ok
     *      the processing for this function has been moved to accept, but this cannot be deleted without creating a compile-time
     *      error. Therefore this function has an empty definition.
     */
    void on_buttonBox_accepted();

    /** fn
     * accept
     *      This slot is overwritten from the QWidget class, it gets called when the user press ok
     *
     * Precondition:
     *      The user should input the name of the customer they are looking for before pressing ok
     *
     * Postcondition:
     *      If the user press ok and the name they have inputted matches a name of a customer in the database then
     *      the main window's searchDatabaseResult function gets called and the QDialog closes. If the user press
     *      ok and the name they inputted does not match any name in the database then an error is displayed informing
     *      the user that the customer was not found.
     */
    void accept();

    /** fn
     * on_buttonBox_rejected
     *      This is the slot that is executed when the user press cancel
     *
     * Postcondition:
     *      The main window's searchDatabaseCancel function is called and the QDialog closes
     */
    void on_buttonBox_rejected();

private:
    Ui::SearchDatabase *ui; //!<Qt's generated ui pointer to access the widgets inside this window

    MainWindow *window; //!<A pointer back to the main window
};

#endif // SEARCHDATABASE_H
